//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridgeDataAccess
{

    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int Quantity_Available { get; set; }
        public decimal Price { get; set; }
        public byte[] Product_Image { get; set; }
        public int Category_Id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
